"""pytest-bdd Bridge Module.

Translates BDD features into pytest-bdd steps, auto-generates missing step
definitions based on target signatures retrieved via MCP tools, runs them
inside the isolated sandbox, and parses JUnit XML reports to collect execution results.
"""

import os
import ast
import json
import xml.etree.ElementTree as ET
import tempfile
import shutil
import asyncio
from typing import List, Dict, Any, Optional, Tuple
from pydantic import BaseModel
from google import genai
from google.genai import types
from dotenv import load_dotenv

from backend.semora.sandbox.runner import get_runner
from semora.mcp.filesystem_server import FilesystemMCPServer

# Load environment variables
load_dotenv()


class StepDefinitions(BaseModel):
    """Schema for structured step definitions code generated by Gemini."""
    python_code: str


def find_function_in_repo(
    repo_path: str,
    function_name: str
) -> Tuple[Optional[str], Optional[Dict[str, Any]]]:
    """Search for the Python file and AST signature of a function in the target repository using MCP tools.

    Args:
        repo_path (str): Absolute path of target repository.
        function_name (str): Name of function to search for.

    Returns:
        Tuple[str, Dict]: Relative path of python file and its signature metadata, or (None, None).
    """
    server = FilesystemMCPServer(repo_root=repo_path)

    async def search() -> Tuple[Optional[str], Optional[Dict[str, Any]]]:
        # 1. List all python files via list_files tool
        _, list_res = await server.mcp.call_tool("list_files", {"pattern": "**/*.py"})
        py_files = list_res.get("result", [])

        # Filter out tests, hidden folders, and virtual environments
        source_files = [
            f for f in py_files
            if not f.startswith("tests/")
            and not f.startswith(".")
            and "venv" not in f
        ]

        for rel_path in source_files:
            # 2. Read each source file via read_file tool
            _, read_res = await server.mcp.call_tool("read_file", {"path": rel_path})
            code_content = read_res.get("result", "")

            # Quick string check first to avoid ast parsing everything
            if f"def {function_name}" in code_content:
                try:
                    tree = ast.parse(code_content)
                    for node in ast.walk(tree):
                        if isinstance(node, ast.FunctionDef) and node.name == function_name:
                            # Parse arguments and returns
                            args_info = []
                            for arg in node.args.args:
                                ann = ast.unparse(arg.annotation) if arg.annotation else "Any"
                                args_info.append((arg.arg, ann))
                            returns = ast.unparse(node.returns) if node.returns else "Any"
                            doc = ast.get_docstring(node) or ""

                            signature = {
                                "name": node.name,
                                "args": args_info,
                                "returns": returns,
                                "docstring": doc
                            }
                            return rel_path, signature
                except Exception:
                    pass
        return None, None

    return asyncio.run(search())


def generate_step_defs_via_gemini(
    feature_content: str,
    feature_filename: str,
    function_name: str,
    module_path: str,
    signature: Dict[str, Any]
) -> str:
    """Invoke the Gemini API to write the python file implementing pytest-bdd step definitions.

    Args:
        feature_content (str): Gherkin feature content.
        feature_filename (str): Name of feature file.
        function_name (str): Name of target function.
        module_path (str): Target module python file path.
        signature (Dict): Parsed function signature.

    Returns:
        str: Executable Python code string for steps.
    """
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        raise ValueError("GEMINI_API_KEY environment variable is not set.")

    client = genai.Client(api_key=api_key)

    # Convert file path to module name: e.g. email_helper.py -> email_helper
    module_name = os.path.splitext(module_path)[0].replace("/", ".").replace("\\", ".")

    prompt = f"""You are an expert pytest-bdd and Gherkin step writer.
Generate complete and executable Python step definitions for the following Gherkin feature.

Gherkin Feature Content:
{feature_content}

Target Function Details:
- Name: {function_name}
- Module Import: `from {module_name} import {function_name}`
- Arguments: {signature['args']}
- Returns: {signature['returns']}
- Docstring: {signature['docstring']}

Guidelines:
1. The output must be written to tests/features/test_{function_name}.py in the target repository.
2. It must load scenarios using scenarios('{feature_filename}').
3. You MUST prepend this standard sys.path override to the top of the file so module imports work correctly:
```python
import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '../..')))
```
4. Define steps using @given, @when, and @then decorators from pytest_bdd.
5. Use a shared state dictionary via a pytest fixture (e.g. test_state) to pass data between steps.
6. The Given step parses and records input (e.g., email strings).
7. The When step calls {function_name}. Catch any expected exceptions (such as TypeError, ValueError) and record the exception object in the shared state (e.g., test_state["exception"]) so it can be verified in the Then step.
8. The Then step asserts that the return value matches the expected boolean, or that the raised exception matches the expected type and message. Do NOT raise unhandled exceptions in the steps themselves.
9. Return ONLY the valid Python code inside the JSON 'python_code' field. Do not include markdown code blocks.
"""

    import time
    max_retries = 5
    delay = 2.0
    for attempt in range(max_retries):
        try:
            response = client.models.generate_content(
                model='gemini-2.5-flash',
                contents=prompt,
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    response_schema=StepDefinitions,
                ),
            )
            break
        except Exception as e:
            if attempt == max_retries - 1:
                raise e
            time.sleep(delay)
            delay *= 2.0

    parsed = response.parsed
    if not parsed or not parsed.python_code:
        raise RuntimeError("Failed to generate step definitions from Gemini API.")

    return parsed.python_code


def parse_junit_xml(xml_path: str) -> List[Dict[str, Any]]:
    """Parse a JUnit XML file to collect test outcome records.

    Returns a list of dicts: name, status, assertion_message, and duration_ms.
    """
    if not os.path.exists(xml_path):
        return []

    try:
        tree = ET.parse(xml_path)
        root = tree.getroot()
        test_cases = []

        for tc in root.iter("testcase"):
            name = tc.get("name", "")
            time_sec = float(tc.get("time", "0.0"))
            duration_ms = time_sec * 1000.0

            status = "passed"
            msg = ""

            failure = tc.find("failure")
            error = tc.find("error")

            if failure is not None:
                status = "failed"
                msg = failure.get("message", "") or (failure.text or "")
            elif error is not None:
                status = "error"
                msg = error.get("message", "") or (error.text or "")

            test_cases.append({
                "name": name,
                "status": status,
                "assertion_message": msg.strip(),
                "duration_ms": duration_ms
            })
        return test_cases
    except Exception as e:
        return [{
            "name": "Parse XML failure",
            "status": "error",
            "assertion_message": f"Failed to parse JUnit XML: {e}",
            "duration_ms": 0.0
        }]


def run_features(
    feature_files: List[str],
    repo_path: Optional[str] = None
) -> Dict[str, Any]:
    """Map BDD features to step definitions and run pytest in the sandbox.

    Args:
        feature_files (List[str]): List of absolute or relative paths to .feature files.
        repo_path (str, optional): Root of target repository. If not given, derived from path.

    Returns:
        Dict[str, Any]: Execution outcome including global passed status and per-spec detail dictionary.
    """
    if not feature_files:
        return {"passed": True, "results": {}}

    # Derive repo_path if missing
    if not repo_path:
        first_file = feature_files[0]
        abs_first = os.path.abspath(first_file)
        repo_path = os.path.dirname(os.path.dirname(os.path.dirname(abs_first)))

    results_ledger = {}
    overall_passed = True

    runner = get_runner()

    for feat_file in feature_files:
        abs_feat_path = os.path.abspath(os.path.join(repo_path, feat_file)) if not os.path.isabs(feat_file) else feat_file
        rel_feat_path = os.path.relpath(abs_feat_path, repo_path)

        # 1. Read the feature file content
        server = FilesystemMCPServer(repo_root=repo_path)

        async def read_feat() -> str:
            _, read_res = await server.mcp.call_tool("read_file", {"path": rel_feat_path})
            return read_res.get("result", "")

        try:
            feat_content = asyncio.run(read_feat())
        except Exception as e:
            overall_passed = False
            results_ledger[feat_file] = {
                "passed": False,
                "tests": [{
                    "name": "Read feature file",
                    "status": "error",
                    "assertion_message": f"Failed to read feature file via MCP: {e}",
                    "duration_ms": 0.0
                }],
                "logs": f"Error: {e}"
            }
            continue

        # 2. Derive function name and locate module file
        func_name = os.path.splitext(os.path.basename(feat_file))[0]
        rel_module_path, signature = find_function_in_repo(repo_path, func_name)

        if not rel_module_path or not signature:
            overall_passed = False
            results_ledger[feat_file] = {
                "passed": False,
                "tests": [{
                    "name": "Locate target function",
                    "status": "error",
                    "assertion_message": f"Could not find function 'def {func_name}' in target repository.",
                    "duration_ms": 0.0
                }],
                "logs": f"Error: Target function {func_name} not found"
            }
            continue

        # 3. Generate the test file with step definitions
        try:
            step_defs_code = generate_step_defs_via_gemini(
                feature_content=feat_content,
                feature_filename=os.path.basename(feat_file),
                function_name=func_name,
                module_path=rel_module_path,
                signature=signature
            )
        except Exception as e:
            overall_passed = False
            results_ledger[feat_file] = {
                "passed": False,
                "tests": [{
                    "name": "Generate step definitions",
                    "status": "error",
                    "assertion_message": f"Failed to generate step definitions via Gemini: {e}",
                    "duration_ms": 0.0
                }],
                "logs": f"Error: {e}"
            }
            continue

        # 4. Write test file alongside the feature file
        features_dir = os.path.join(repo_path, "tests", "features")
        os.makedirs(features_dir, exist_ok=True)
        test_file_path = os.path.join(features_dir, f"test_{func_name}.py")

        with open(test_file_path, "w", encoding="utf-8") as f:
            f.write(step_defs_code)

        # 5. Run pytest in the sandbox, writing results to XML report
        sandbox_temp = tempfile.mkdtemp(prefix="semora-sandbox-run-")
        try:
            rel_test_file = os.path.relpath(test_file_path, repo_path)
            xml_report = os.path.join(sandbox_temp, "report.xml")

            command = f"pytest -p no:cacheprovider --junitxml={xml_report} {rel_test_file}"
            run_res = runner.run(command=command, temp_dir=sandbox_temp, repo_path=repo_path)

            # Parse report.xml
            test_cases = parse_junit_xml(xml_report)

            # Determine if this spec suite passed
            spec_passed = (run_res.get("status") == "SUCCESS" and
                           all(tc["status"] == "passed" for tc in test_cases))

            if not spec_passed:
                overall_passed = False

            # Add to ledger
            results_ledger[feat_file] = {
                "passed": spec_passed,
                "tests": test_cases if test_cases else [{
                    "name": "Execution wrapper",
                    "status": "failed" if run_res.get("status") == "SANDBOX_VIOLATION" else "error",
                    "assertion_message": run_res.get("stderr", "Unknown sandbox error"),
                    "duration_ms": 0.0
                }],
                "logs": f"STDOUT:\n{run_res.get('stdout', '')}\nSTDERR:\n{run_res.get('stderr', '')}"
            }

        finally:
            shutil.rmtree(sandbox_temp)

    return {
        "passed": overall_passed,
        "results": results_ledger
    }
