"""State Management for the ADK Graph Workflow.

Defines the configuration, context, and shared state data exchanged between
agents during a quality-gate execution.
"""

from typing import Any, Optional
from pydantic import BaseModel, Field


class RunState(BaseModel):
    """
    Shared state schema for the Semora ADK Graph Workflow.
    This state is passed between the Spec, Execution, Threat, and Aggregator nodes.
    """
    repo_path: str = Field(
        description="The absolute or relative path to the repository being analyzed."
    )
    diff_text: str = Field(
        description="The raw diff text (e.g., from git) representing the changes to analyze."
    )
    generated_specs: list[str] = Field(
        default_factory=list,
        description="A list of file paths pointing to the test specifications generated by the Spec node."
    )
    execution_results: dict[str, Any] = Field(
        default_factory=dict,
        description="A pass/fail ledger of test executions, populated by the Execution node. "
                    "Expected shape: { 'spec_file_path': { 'passed': bool, 'logs': str, ... } }."
    )
    threat_findings: list[dict[str, Any]] = Field(
        default_factory=list,
        description="A list of security threat findings, populated by the Threat node. "
                    "Expected shape: [ { 'severity': str, 'description': str, 'location': str }, ... ]."
    )
    compliance_score: Optional[int] = Field(
        default=None,
        description="An aggregated integer compliance score (0-100), populated by the Aggregator node based on executions and threats."
    )
